#!/bin/bash

### GRAB - Script for grabbing camera images from Android FTP server and creating a video timelapse from the images. 

### Script downloads images to a date directory, removes remote files, creates video using FFMPEG, then removes local image files.

HOST='192.168.0.10 2221'
USER='camera'
PASSWD='camera'
TODAY=$(date +%m%d%y)

if [ ! -d $TODAY ]
  then
    mkdir $TODAY
fi

cd $TODAY

### FTP (requires .netrc)

ftp -pi $HOST << EOT
binary
user $USER $PASSWD
mget *
mdelete *
bye
EOT

cd ..
### FFMPEG

ffmpeg -framerate 30 -pattern_type glob -i "$TODAY/IMG_*.jpg" -vf scale=1920:1080 $TODAY.mp4

